name: Build and publish compliance reports
on:
  schedule:
    - cron: "0 0 * * 6" # Run at 00:00 on every saturday
  push:
    branches:
      - master
      - main
jobs:
  build-and-publish:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          node dist/src/index.js -s ${{ secrets.PINATA_API_ENDPOINT }} ${{ secrets.PINATA_API_TOKEN }} -s ${{ secrets.ESTUARY_API_ENDPOINT }} ${{ secrets.ESTUARY_API_TOKEN }} -s ${{ secrets.NFT_API_ENDPOINT }} ${{ secrets.NFT_API_TOKEN }} -s ${{ secrets.WEB3_API_ENDPOINT }} ${{ secrets.WEB3_API_TOKEN }}

      # Deploy to gh pages branch
      - name: Deploy
        uses: s0/git-publish-subdir-action@399aab378450f99b7de6767f62b0d1dbfcb58b53
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
