name: Build and publish compliance reports
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # Run at 00:00 on every saturday
  push:
    branches:
      - master
      - main
  pull_request:
    branches: [ main ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: ipfs/aegir/actions/cache-node-modules@master
  pinata-compliance-checks:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run dev-start -- -s ${{ secrets.PINATA_API_ENDPOINT }} ${{secrets.PINATA_API_TOKEN}}
  estuary-compliance-checks:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run dev-start -- -s ${{ secrets.ESTUARY_API_ENDPOINT }} ${{secrets.ESTUARY_API_TOKEN}}
  nft-compliance-checks:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run dev-start -- -s ${{ secrets.NFT_API_ENDPOINT }} ${{secrets.NFT_API_TOKEN}}
  web3-compliance-checks:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run dev-start -- -s ${{ secrets.WEB3_API_ENDPOINT }} ${{secrets.WEB3_API_TOKEN}}

  # Deploy to gh pages branch
  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: [pinata-compliance-checks, estuary-compliance-checks, nft-compliance-checks, web3-compliance-checks]
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      ## Cron jobs
      - name: Scheduled deployment
        if: github.event.schedule != null || github.event.pusher != null
        uses: s0/git-publish-subdir-action@399aab378450f99b7de6767f62b0d1dbfcb58b53
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ## PRs should push to branch other than primary `gh-pages` branch
      - name: Deployment for PR
        if: github.event.pull_request != null
        uses: s0/git-publish-subdir-action@399aab378450f99b7de6767f62b0d1dbfcb58b53
        env:
          REPO: self
          BRANCH: gh-pages-${{github.sha}}
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
